name: Fetch Thunderstore Mod Data

on:
  workflow_dispatch:
  schedule:
    # Run at 8am UTC (12am PST)
    - cron: "0 8 * * *"
    # cron formatting:
    # 0 = minute
    # 8 = 8am UTC
    # * = Every day of month
    # * = Every month of year
    # * = Every day of week

jobs:
  get-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch mod data from Thunderstore and print contents
        run: |
          curl -v -o data.json https://thunderstore.io/api/v1/package-metrics/Plotection/MoneyForKills/
          echo "Contents:"
          cat data.json

      - name: Validate fetched data and date
        run: |
          if [ ! -s data.json ]; then
            echo "data.json is empty"
            exit 1
          fi
          echo "Current time and date is: $(date +'%m/%d/%y %H:%M')"

      - name: Commit fetched data to repo
        shell: bash
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Update data.json with latest data from ($(date +'%m/%d/%y %H:%M'))"
          git push

      - name: Install Node.js
        uses: actions/install-node@v4
        with:
          node-version: "22"

      - name: Install dependencies, if any
        run: npm install

      - name: Run update-database.js to upload data to modmetrics.db
        run: node update-database.js

      - name: Commit updated database to repo
        shell: bash
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add modmetrics.db
          git commit -m "Update database using data.json from ($(date +'%m/%d/%y %H:%M'))"
          git push
